FROM quay-proxy.ci.openshift.org/openshift/ci:ocp_builder_rhel-9-golang-1.24-openshift-4.20 AS builder
WORKDIR /go/src/github.com/kubernetes-sigs/vsphere-csi-driver
COPY . .
RUN make build # TODO: build only driver

FROM quay-proxy.ci.openshift.org/openshift/ci:ocp_4.20_base-rhel9
COPY --from=builder /go/src/github.com/kubernetes-sigs/vsphere-csi-driver/.build/bin/syncer.linux_amd64  /usr/bin/vmware-vsphere-csi-driver-syncer
ENTRYPOINT ["/usr/bin/vmware-vsphere-csi-driver-syncer"]
